In [1]:
from datetime import datetime

import pandas as pd

In [2]:
noahs_customers = pd.read_csv("../noahs-customers.csv")

noahs_orders_items = pd.read_csv("../noahs-orders_items.csv")

noahs_orders = pd.read_csv("../noahs-orders.csv")

noahs_products = pd.read_csv("../noahs-products.csv")

In [3]:
# Format the orders DataFrame

noahs_orders['shipped'] = pd.to_datetime(noahs_orders['shipped'])

noahs_orders["shipping_date"] = noahs_orders["shipped"].apply(
    lambda x: x.strftime("%Y-%m-%d"))

In [4]:
noahs_customers_and_orders = pd.merge(noahs_customers, noahs_orders, how="inner", on="customerid")

noahs_products_and_orders_items = pd.merge(noahs_products, noahs_orders_items, how="inner", on="sku")

noahs_aggregated_df = pd.merge(noahs_customers_and_orders, noahs_products_and_orders_items, how="inner", on="orderid")

In [5]:
# Find the customer id of the person from previous puzzle

initial_person_customerid = noahs_customers[noahs_customers["phone"]
                                            == "585-838-9161"]["customerid"].iloc[0]

initial_person_customerid

4167

In [6]:
noahs_aggregated_df_initial_person_customerid = noahs_aggregated_df[noahs_aggregated_df["customerid"] == initial_person_customerid]

noahs_aggregated_df_initial_person_customerid

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long,orderid,...,shipped,items,total,shipping_date,sku,desc,wholesale_cost,dims_cm,qty,unit_price
167929,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,11265,...,2017-05-13 15:00:00,NaN,9.11,2017-05-13,TOY0481,Automatic Board Game,15.64,10.4|9.6|1.8,1,9.11
167930,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,15650,...,2017-06-26 19:48:36,NaN,16.74,2017-06-26,TOY1479,Star Wars Doll,22.55,14.2|5.6|3.4,1,11.79
167931,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,15650,...,2017-06-26 19:48:36,NaN,16.74,2017-06-26,HOM2761,Rug Cleaner,1.43,19.6|11.7|0.2,1,0.99
167932,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,15650,...,2017-06-26 19:48:36,NaN,16.74,2017-06-26,PET3443,"Gluten-free Senior Cat Food, Chicken & Chicken",1.45,18.5|18.4|2.5,1,0.99
167933,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,15650,...,2017-06-26 19:48:36,NaN,16.74,2017-06-26,PET7145,"Wet Cat Food, Turkey & Turkey",1.06,18.0|9.3|9.1,1,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167985,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,180771,...,2022-01-13 18:37:23,NaN,13.62,2022-01-13,TOY7389,Star Wars Board Game,25.77,8.8|8.2|0.3,1,13.62
167986,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,184612,...,2022-02-21 10:06:09,NaN,0.99,2022-02-21,PET4284,"Wet Adult Cat Food, Beef & Beef",0.75,15.2|14.0|2.2,1,0.99
167987,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,190610,...,2022-04-23 18:45:00,NaN,3.05,2022-04-23,PET2899,"Dry Cat Food, Duck & Duck",1.14,18.7|12.0|0.3,1,0.99
167988,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,190610,...,2022-04-23 18:45:00,NaN,3.05,2022-04-23,COL7663,Noah's Poster (white),4.07,5.6|4.8|4.1,1,2.06
167989,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,200309,...,2022-07-30 13:00:00,NaN,0.99,2022-07-30,DLI6168,Salted Cucumber Salad,1.03,19.2|12.3|1.6,1,0.99

In [7]:
colours = [
    "red", "blue", "green", "yellow", "purple",
    "orange", "pink", "brown", "black", "white",
    "gray", "cyan", "magenta", "teal", "indigo",
    "violet", "gold", "silver", "beige", "maroon"
]


def check_desc_colours(desc_name: str) -> str | None:

    for colour in colours:

        if colour in desc_name:

            return colour

    return None

In [8]:
noahs_aggregated_df_initial_person_customerid["colour"] = noahs_aggregated_df_initial_person_customerid["desc"].apply(check_desc_colours)

noahs_aggregated_df_initial_person_customerid_colour = noahs_aggregated_df_initial_person_customerid.dropna(subset=["colour"])

noahs_aggregated_df_initial_person_customerid_colour

/var/folders/22/81pdbfvd4nn4qrrp_t9990tm0000gn/T/ipykernel_60153/1346015826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  noahs_aggregated_df_initial_person_customerid["colour"] = noahs_aggregated_df_initial_person_customerid["desc"].apply(check_desc_colours)

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long,orderid,...,items,total,shipping_date,sku,desc,wholesale_cost,dims_cm,qty,unit_price,colour
167971,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,124821,...,NaN,13.04,2020-06-28,COL7955,Noah's Action Figure (green),12.96,8.8|6.8|1.5,2,6.52,green
167981,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,170967,...,NaN,6.65,2021-10-07,COL6858,Noah's Jersey (blue),10.60,16.0|6.6|4.0,1,5.66,blue
167988,4167,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.8182,-73.86752,190610,...,NaN,3.05,2022-04-23,COL7663,Noah's Poster (white),4.07,5.6|4.8|4.1,1,2.06,white

In [9]:
def extract_item_desc(desc_name: str) -> str:

    if "(" not in desc_name or ")" not in desc_name:

        return extract_item_desc
    
    open_bracket_index = desc_name.index("(")

    return desc_name[open_bracket_index:]

In [ ]:
noahs_initial_person_customerid_possible_dates_desc = list(noahs_aggregated_df_initial_person_customerid_colour["shipping_date"].unique())

In [ ]:
noahs_aggregated_df_match = noahs_aggregated_df[noahs_aggregated_df["shipping_date"]]